### ISSUE TITLE
Leading slash on paths in index.html prevents running in a subdirectory

### ISSUE THREAD

**Issue by hubgit** [yeoman/generator-polymer#161]
[A recent commit](https://github.com/yeoman/generator-polymer/commit/6458a4db3432f678546d840324728c3aee4af45a#diff-e5350545d9d767aaa6f4946fcef153aeL11) added leading slashes to paths in index.html. 

Unfortunately, this means that applications not running at the root path (e.g. project sites on GitHub Pages) no longer load their dependencies correctly.

**Comment by kevva** [comment]
ping @robdodson

**Comment by hubgit** [comment]
I'm still having an issue with paths when building with Gulp and deploying to GitHub Pages. 

In `elements.vulcanized.html` the include paths begin with `../../bower_components/` but they need to be `../bower_components/`, as the `bower_components` folder gets moved up a level when building into the `dist` folder.

**Comment by robdodson** [comment]
Darn, I wish we had never moved the directory but that was [a recommendation](http://yeoman.io/blog/bower_components-in-project-root.html) from the rest of the team.

@eddiemonge how're you dealing with this in the Angular generator? I think if I can't use a leading slash then I have to rewrite bower_components paths everywhere in my app. Since most polymer elements have to link back to bower_components/polymer/polymer.html, that's potentially a lot of rewrites.

**Comment by eddiemonge** [comment]
Its a tricky situation but compounded even more in Angular since most Angular apps I would say are single page apps written to work off one index.html file. Absolute paths there are the norm. Relative paths are hard to do there but are handled with a base tag. You could change the build system so the re-written file paths are relative at the end of the build process.

**Comment by robdodson** [comment]
I see. I would like to avoid rewriting anyone's code if I can help it, the less work the generator has to do the less room there is for bugs. Given that Polymer also has a vulcanize step which concatenates HTML Imports and uses `assetPath` to reach back to the original dir if it needs assets like images, I'm feeling like touching people's paths is maybe a potentially brittle or error prone option. I think I'd like to move bower_components back to app and strip out the code that does all the fancy rewriting.

@sindresorhus @addyosmani do you guys have objections to this?

**Comment by ragingwind** [comment]
@robdodson I think, vulcanize supports more options to manage asset path. like a `routes` options of browersync for between real-asset-path('../bower_components') and output-asset-path('/bower_components) written in vulcanised file. it would be better then touching outside by build system.

**Comment by robdodson** [comment]
@ragingwind that would be good, but it doesn't change the fact that we also would need to rewrite any path in the app that is trying to get to bower_components. If bower_components is in the app dir, we avoid all of this.

**Comment by ragingwind** [comment]
I think that is not rewrite, just change or map :)

**Comment by eddiemonge** [comment]
> and In the case of chrome apps bower_components must be in the app dir

In the build files it will be. The biggest problem to having bc outside of app dir is the build tools. Its my strong belief that build tools should be smart enough to have bc outside but build/preview it to be inside the dir virtually. I still feel like code inside /app should be purely user code. They shouldn't worry about it changing on them without their input. Build tools shouldn't rely on the path thats in the user code to be the actual path on the file system. 

Having said that, I know its easier said than done to make that happen. If Vulcanize needs support to handle this case I'd be happy to help with it but doubt I'd make any real contributions anytime soon due to my very limited free time, but I'd contribute what/when I could if wanted.

**Comment by robdodson** [comment]
@hubgit can you try [this branch](https://github.com/yeoman/generator-polymer/tree/path-fixup) and let me know if it fixes your issue?

You can clone the branch, cd into the directory, and run `npm link`, then create a new directory on your desktop, cd in, and run `yo polymer` like usual.

I think since BrowserSync is treating `app` as `/` then I should be able to use the same path for `bower_components` in dev and dist and there's no need to rewrite any paths. It seems to be working ok for me, even if I nest my project in subdirectories. Just want to verify it works for you before moving ahead.

**Comment by ragingwind** [comment]
@eddiemonge I agree with you. bc is not part of user code. but I could not found a graceful solutions to solve the problem of chrome apps/extension generator. To preview an app, bc need to be placed in app. It would be great If you help to improve anytime

**Comment by hubgit** [comment]
@robdodson That seems to work, with a simple test of gulp build + deploy to gh-pages.

**Comment by robdodson** [comment]
@ragingwind I think the changes I made in the recent branch fixes the issue for regular web apps but I didn't realize there was also this problem with chrome apps :(

I'm going to push this fix and open another ticket for supporting chrome apps.

**Comment by robdodson** [comment]
Fixed in ae218de1cb5697d61186c31dc136b973f70430c9
