### ISSUE TITLE
No Grunt File

### ISSUE THREAD

**Issue by tmess567** [yeoman/generator-polymer#184]
Gulp is new for me and it would really help if this generator included a grunt file.

**Comment by kevva** [comment]
Learn gulp. We decided to go with gulp in https://github.com/yeoman/generator-polymer/pull/127.

**Comment by tmess567** [comment]
Well could you help me out...
I tried looking for a solution on google but nothing came up

i run "$ gulp test:local" as suggested in the manual
2 windows pop up (a chrome and a firefox)
none of them show anything on the page or the source....

**Comment by kevva** [comment]
https://github.com/yeoman/generator-polymer/tree/master/app/templates/polymer-starter-kit.

**Comment by tmess567** [comment]
Oh thankyou so much works like a charm....
Didn't see this page before...
:P

**Comment by robdodson** [comment]
@tmess567 yeah sorry for the sudden change, we used to support grunt but have been focusing more on having a more "opinionated" toolchain. Because there are so many tools for developers to choose from, it can actually become really overwhelming. Addy wrote a great article on this last year: http://addyosmani.com/blog/front-end-choice-paralysis/

This is also reflected in the approach to our Web Fundamentals project. For instance, [the tools section](https://developers.google.com/web/fundamentals/tools/index?hl=en) is very prescriptive, and that's by design. By narrowing our focus to a limited set of tools, we can help more developers get on the quick path to building their app, vs having to spend tons of time researching the pros and cons of all the different things out there.

**Comment by tmess567** [comment]
That explains it...
Thanks
