### ISSUE TITLE
Deploy on Github pages not working

### ISSUE THREAD

**Issue by Granze** [yeoman/generator-polymer#40]
When I run `yo polymer:gh` I get two errors during the script execution:
`gp.sh: 16: gp.sh: pushd: not found` at the beginning
and
```
gp.sh: 34: gp.sh: popd: not found

child process exited with code 127
``` 
at the end.

I'm on Ubuntu 14.04, I usually use zsh as default but I've tryed bash as well without success.

If I run e.g. `pushd . ` directly, the command works.

**Comment by MasterAM** [comment]
I guess that this is related to the fact that in Ubuntu `sh` is linked to the `dash` shell, and the latter lacks support for `pushd` and `popd`, among other things.

I was also affected by this issue and had to run it manually in order to generate GH pages properly.

@robdodson Will you consider spawning `bash` instead of `sh`? That fixed it for me.

**Comment by robdodson** [comment]
@MasterAM ok yeah we can give that a shot

**Comment by twixie** [comment]
I am having this problem too. 

> Will you consider spawning bash instead of sh? That fixed it for me.

Seems to fix it for me though I'm still seeing another error.

**Comment by pascal-de-ladurantaye** [comment]
For the lazy:
```bash
sudo npm install -g git://github.com/yeoman/generator-polymer#master
```
This will fetch the master version of the generator which contains the fix.

**Comment by robdodson** [comment]
I plan to roll out a new release soon which will contain the fix. Usually you don't want to install from master because it's not guaranteed stable.

**Comment by pascal-de-ladurantaye** [comment]
I totally agree with you, this is a temporary solution for the issue while the fix has not been released :)

**Comment by robdodson** [comment]
I know :) I wanted to leave that comment in case folks come around after the release and still decide to install from amster

**Comment by pascal-de-ladurantaye** [comment]
Hey, just a heads up, installing the generator with npm through git will not resolve the git submodules thus breaking the generator since it uses polymer-starter-kit and seed-element through submodules.

Better yet, you will have to `sudo npm cache clean` because it keeps the broken version in cache.

Finally, to fix the issue, you will have to manually edit the /usr/local/lib/node_modules/generator-polymer/gh/index.js to spawn bash instead of sh.

**Comment by robdodson** [comment]
> installing the generator with npm through git

Yeah if you're pulling down a clone of it I guess that would happen. I believe when we do releases the submodules get tarballed up so you don't have to worry about it. I'll push out a new release today.
